export const NS = {
  dat: "http://www.stormware.cz/schema/version_2/data.xsd",
  rsp: "http://www.stormware.cz/schema/version_2/response.xsd",
  rdc: "http://www.stormware.cz/schema/version_2/documentresponse.xsd",
  typ: "http://www.stormware.cz/schema/version_2/type.xsd",
  lst: "http://www.stormware.cz/schema/version_2/list.xsd",
  lStk: "http://www.stormware.cz/schema/version_2/list_stock.xsd",
  lAdb: "http://www.stormware.cz/schema/version_2/list_addBook.xsd",
  lCon: "http://www.stormware.cz/schema/version_2/list_contract.xsd",
  lAcv: "http://www.stormware.cz/schema/version_2/list_activity.xsd",
  lCen: "http://www.stormware.cz/schema/version_2/list_centre.xsd",
  ftr: "http://www.stormware.cz/schema/version_2/filter.xsd",
  prn: "http://www.stormware.cz/schema/version_2/print.xsd",
  inv: "http://www.stormware.cz/schema/version_2/invoice.xsd",
  ord: "http://www.stormware.cz/schema/version_2/order.xsd",
  ofr: "http://www.stormware.cz/schema/version_2/offer.xsd",
  enq: "http://www.stormware.cz/schema/version_2/enquiry.xsd",
  vch: "http://www.stormware.cz/schema/version_2/voucher.xsd",
  int: "http://www.stormware.cz/schema/version_2/intDoc.xsd",
  bnk: "http://www.stormware.cz/schema/version_2/bank.xsd",
  stk: "http://www.stormware.cz/schema/version_2/stock.xsd",
  adb: "http://www.stormware.cz/schema/version_2/addressbook.xsd",
  con: "http://www.stormware.cz/schema/version_2/contract.xsd",
  pri: "http://www.stormware.cz/schema/version_2/prijemka.xsd",
  vyd: "http://www.stormware.cz/schema/version_2/vydejka.xsd",
  pro: "http://www.stormware.cz/schema/version_2/prodejka.xsd",
  pre: "http://www.stormware.cz/schema/version_2/prevodka.xsd",
  vyr: "http://www.stormware.cz/schema/version_2/vyroba.xsd",
  ser: "http://www.stormware.cz/schema/version_2/service.xsd",
  bal: "http://www.stormware.cz/schema/version_2/balance.xsd",
  act: "http://www.stormware.cz/schema/version_2/accountancy.xsd",
  sto: "http://www.stormware.cz/schema/version_2/store.xsd",
  str: "http://www.stormware.cz/schema/version_2/storage.xsd",
  ctg: "http://www.stormware.cz/schema/version_2/category.xsd",
  nms: "http://www.stormware.cz/schema/version_2/numericalSeries.xsd",
  pay: "http://www.stormware.cz/schema/version_2/payment.xsd",
  cas: "http://www.stormware.cz/schema/version_2/cashRegister.xsd",
  bka: "http://www.stormware.cz/schema/version_2/bankAccount.xsd",
  cls: "http://www.stormware.cz/schema/version_2/classificationVAT.xsd",
  mov: "http://www.stormware.cz/schema/version_2/movement.xsd",
  sup: "http://www.stormware.cz/schema/version_2/supplier.xsd",
  idp: "http://www.stormware.cz/schema/version_2/individualprice.xsd",
  acr: "http://www.stormware.cz/schema/version_2/actionPrice.xsd",
  ipm: "http://www.stormware.cz/schema/version_2/inventoryLists.xsd",
  prq: "http://www.stormware.cz/schema/version_2/productRequirement.xsd",
  rgn: "http://www.stormware.cz/schema/version_2/registrationNumber.xsd",
  rec: "http://www.stormware.cz/schema/version_2/recyclingContrib.xsd",
  clm: "http://www.stormware.cz/schema/version_2/claim.xsd",
  acu: "http://www.stormware.cz/schema/version_2/accountingunit.xsd",
  afp: "http://www.stormware.cz/schema/version_2/automaticLiquidation.xsd",
  rul: "http://www.stormware.cz/schema/version_2/rulesPairing.xsd",
  dis: "http://www.stormware.cz/schema/version_2/discount.xsd",
} as const;

export const POHODA_VERSION = "2.0";
export const POHODA_APP_NAME = "pohoda-mcp";
